header:
    version: 8

machine: refdes-me-aa1-270-2i2-d11e-nfx3-pe1
# machine: refdes-me-aa1-270-2i2-d11e-nfx3-pe3
# machine: refdes-me-aa1-270-2i2-d11e-nfx3-st1
# machine: refdes-me-aa1-270-3e4-d11e-nfx3-pe1
# machine: refdes-me-aa1-270-3e4-d11e-nfx3-pe3
# machine: refdes-me-aa1-270-3e4-d11e-nfx3-st1
# machine: refdes-me-aa1-480-2i3-d12e-nfx3-pe1
# machine: refdes-me-aa1-480-2i3-d12e-nfx3-pe3
# machine: refdes-me-aa1-480-2i3-d12e-nfx3-st1
# machine: refdes-me-sa1-c6-7i-d10-pe1
# machine: refdes-me-sa1-c6-7i-d10-pe3
# machine: refdes-me-sa1-c6-7i-d10-st1
# machine: refdes-me-sa2-d6-7i-d11-pe1
# machine: refdes-me-sa2-d6-7i-d11-pe3
# machine: refdes-me-sa2-d6-7i-d11-st1

distro: nodistro

target: image-minimal-refdes

env:
    UBOOT_CONFIG: sdmmc
#    UBOOT_CONFIG: emmc
#    UBOOT_CONFIG: qspi

repos:

    bitbake:
        url: "https://git.openembedded.org/bitbake"
        refspec: 2023-04.2-mickledore
        layers:
            .: excluded

    openembedded-core:
        url: "https://git.openembedded.org/openembedded-core"
        refspec: 2023-04.2-mickledore
        layers:
            meta:

    meta-intel-fpga:
        url: "https://git.yoctoproject.org/meta-intel-fpga"
        refspec: mickledore

    meta-enclustra-socfpga:
        layers:
            meta-enclustra-module:
            meta-enclustra-refdes:

    meta-openembedded:
        url: http://git.openembedded.org/meta-openembedded
        refspec: mickledore
        layers:
            meta-oe:
            meta-python:
            meta-networking:

local_conf_header:
    meta-enclustra-socfpga: |
        PACKAGE_CLASSES ?= "package_ipk"
        PATCHRESOLVE = "noop"
        EXTRA_IMAGE_FEATURES:append = " ssh-server-dropbear"
        EXTRA_IMAGE_FEATURES:append = " debug-tweaks"
        require conf/distro/include/no-static-libs.inc
        require conf/distro/include/yocto-uninative.inc
        require conf/distro/include/security_flags.inc
        INHERIT:append = " uninative"
        DISTRO_FEATURES:append = " largefile systemd "
        VIRTUAL-RUNTIME_init_manager = "systemd"
        PREFERRED_VERSION_u-boot-socfpga = "v2023.01%"
